spring:
  application:
    name: oauth
    devtoken: DevToken eyJraWQiOiIyZGRlYjFjYjM5IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiI5MzlkN2RlNi1hZTY5LTRlMGUtYTM2Yy1lZTljOTJiN2E1YzUiLCJzdWIiOiI2YTczNjYyNS03MWJhLTRhYjQtOWRkNy1jYTY3NDAzOGMxN2MiLCJleHAiOjE3MzcxNjM1MTIsImlhdCI6MTczNTk1MzkxMn0.LZYbkGU-9zJXsQBpOvFihvLqKUCpeS3EeStKW7IA-HdTQkd_o6pOh27RJgKyin8bahwGZa14Z_0BNG3LEV7suw
  datasource:
    url: jdbc:mysql://localhost:3307/transferase
    username: mehdi
    password: 1234

# set to trace
logging:
  level:
    org.springframework.security: TRACE


