spring:
  application:
    name: oauth
    devtoken: eyJhbGciOiJFUzI1NiIsImtpZCI6IjMzMTE4OTRkNDkifQ.eyJpc3MiOiIyY2Y4MmRiMy00MDY0LTQyMzUtODI1My0xNjk5NGViNTE3NzMiLCJpYXQiOjE3MzYxODA5NTMuODM5LCJleHAiOjE3MzczOTA1NTMuODM5fQ.g30g5E_dXpK36A6Y3CdhG1CAjUmh0o6JeXQn8JRce0BfVGDMczQsdQkq2Qx4A2fNV9AWt-Gp3gNnHHfkoxDM6w
  datasource:
    url: jdbc:mysql://localhost:3307/transferase
    username: mehdi
    password: 1234

# set to trace
logging:
  level:
    org.springframework.security: TRACE


