spring:
  application:
    name: oauth
  datasource:
    url: jdbc:mysql://localhost:3307/transferase
    username: mehdi
    password: 1234

# set to trace
logging:
  level:
    org.springframework.security: TRACE
